### ISSUE TITLE
Cookies file locked

### ISSUE THREAD

**Issue by ThatJeffGuy** [nartos9090/freepik-downloader#2]
Most newer browsers, tried with Friefox, Brave (Chromium), and Edge, all store their cookies in a single file which isn't readable or extractable.

How can you point the cookie with this change in the way cookies are handled?

**Comment by nartos9090** [comment]
Cookie are always sent to the server on every HTTP request. By using the browser devtools, you can get the cookie on the network tab. There are HTTP request sent when you open freepik.com page. Just copy the cookie from the request headers.
Currently i'm using chrome, but every browsers have their own devtools. Especially for chromium based browser such as Brave and Edge.

**Comment by devingfx** [comment]
Hi!
Could you name the cookie(s) to copy/paste please?
Does this downloader work with normal account (aka 10 downloads limit) ?

**Comment by nartos9090** [comment]
I just copy all the cookie text, because i don't now exactly the cookie needed to make the browser logged in automatically.
This downloader will work even with normal account. This script works by pressing the download button with defined query selector in the puppetteer.ts file. If if doesn't work because normal account and premium account has different button, or when the website update the button class or else, you can update the query selector to make it work.

**Comment by devingfx** [comment]
Thx for the reply, I'll test that but later...

**Comment by novakand** [comment]
Hello. Something has changed in cookies, previously copied everything worked. Now the error. Apparently something has been changed in the сookie line.

**Comment by nartos9090** [comment]
I have updated the script for those error, but i'm not sure, so let me know if it still doesn't work on your device.
I also updated the puppeteer version and added env config for puppeteer to customize the executable path, headless mode, and args for my ARM64 server, but x64 device could ran without those config.

> Hello. Something has changed in cookies, previously copied everything worked. Now the error. Apparently something has been changed in the сookie line.

**Comment by novakand** [comment]
Good afternoon. Thank you! I'll try how it works. On the basis of your script, I also want to make access to envato elements, but so far it doesn’t work by analogy, apparently the cookie has some kind of protection!

**Comment by novakand** [comment]
Thanks again! Works!
